//Search Actions
export const FETCHING_SEARCHRESULTS = 'FETCHING_SEARCHRESULTS'
export const FETCHING_SEARCHRESULTS_SUCCESS = 'FETCHING_SEARCHRESULTS_SUCCESS'
export const FETCHING_SEARCHRESULTS_FAILURE = 'FETCHING_SEARCHRESULTS_FAILURE'
export const CHANGE_SEARCH_CATEGORY = 'CHANGE_SEARCH_CATEGORY'
export const CHANGE_SEARCH_DISTANCE = 'CHANGE_SEARCH_DISTANCE'
export const CHANGE_SEARCH_TERM = 'CHANGE_SEARCH_TERM'
